name: Build and deploy JAR app to Azure Web App - touristguideandensemester

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Show directory structure
        run: ls -R

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Find og byg projekt
      - name: Build with Maven
        run: mvn -B clean install -f $(find . -name "pom.xml" -maxdepth 2)

      # Upload det byggede JAR artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: $(find . -name "*.jar" -path "*/target/*" -maxdepth 4)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Show downloaded files
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_29589EEBC84F4EF2BC1D2C45E4D34303 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4638540B00F340D5B1A015461BB386B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B82C9AC915F84659BFAB334C3C757123 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'touristguideandensemester'
          slot-name: 'Production'
          package: '*.jar'
